### ISSUE TITLE
Media Sync failing

### ISSUE THREAD

**Issue by PartTheSeas** [mregni/EmbyStat#899] opened 2019-08-12 15:21 UTC
# Bug report

**Describe the bug**
Media Sync not completing anymore after update to beta10

**Logs**
[2019-08-12.log](https://github.com/mregni/EmbyStat/files/3493198/2019-08-12.log)

**System (please complete the following information):**

- OS: Win 10
- Browser Chrome
- Version beta10

Please see the logs assigned Mr. regni :) Media Syncing just isn't working anymore :(

Have a great start into the week!

**Comment by Happy2Play** [comment] 2019-08-12 21:44
Task completes but no movies or shows, with this error in log.

> 19-08-12 14:41:55.5118 [INFO] THETVDB-CLIENT Calling TheTVDB to udpated shows
2019-08-12 14:41:55.5118 [INFO] THETVDB-CLIENT Call to THETVDB: https://api.thetvdb.com/updated/query?fromTime=1565640622&toTime=1566245422
2019-08-12 14:41:55.6204 [ERROR] THETVDB-CLIENT Could not receive show list from TVDB MediaBrowser.Model.Net.HttpException: One or more errors occurred. (The remote server returned an error: (401) Unauthorized.) ---> System.AggregateException: One or more errors occurred. (The remote server returned an error: (401) Unauthorized.) ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of inner exception stack trace ---
at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 54
--- End of inner exception stack trace ---
at EmbyStat.Common.Net.HttpWebRequestClient.GetResponse(HttpRequest options, Boolean sendFailureResponse) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 80
at EmbyStat.Common.Net.HttpWebRequestClient.SendAsync(HttpRequest options) in d:\a\1\s\EmbyStat.Common\Net\HttpWebRequestClient.cs:line 111
at EmbyStat.Clients.Tvdb.TvdbClient.GetShowsToUpdate(IEnumerable`1 showIds, DateTime lastUpdateTime, CancellationToken cancellationToken) in d:\a\1\s\EmbyStat.Clients.Tvdb\TvdbClient.cs:line

**Comment by PartTheSeas** [comment] 2019-08-12 22:11
Oh! Thank you for pointing me to the right direction.

I double checked and EmbyStat doesn't take my admin password. Copy pasted it from the clipboard. Working on Emby but not on Embystat

**Comment by PartTheSeas** [comment] 2019-08-12 22:19
I don't know why, but it's working after a fresh install. It just wouldn't take my admin password, now it's working 🎉

**Comment by Happy2Play** [comment] 2019-08-12 22:30
Mine is working now also,  I can only assume there was a TVDB issue as I am seeing v2 - v3 api issues in other programs.  But EmbyStats has successful ran a media sync on .10.

**Comment by rTiGd2** [comment] 2019-08-16 17:24
I had this problem then read the note about "remove the previous install or 0.9 or older" because the config of .10 has changes that aren't forward compatible.

**Comment by mregni** [comment] 2019-08-17 10:09
Glad it's working again in the .10 version. I forgot to mention you needed a clean install for the .10 version. Sorry about that.

**Comment by mregni** [comment] 2019-09-23 11:07
Closing this because it looks like the issue is fixed after the clean beta.10 install.

**Closed as completed by mregni** 2019-09-23 11:07 UTC
