### ISSUE TITLE
failed to perform media sync task the second and subsequent times

### ISSUE THREAD

**Issue by saeddd** [mregni/EmbyStat#1169] opened 2020-04-15 11:33 UTC
[2020-04-15 (2).log](https://github.com/mregni/EmbyStat/files/4480917/2020-04-15.2.log)
# Bug report

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

- OS: [e.g. Windows, Ubuntu]

**Additional context**

**Comment by mregni** [comment] 2020-04-20 20:52
Duplicate of #1156, this should be fixed normally in the new beta.19 release. 
If not, feel free to comment it that issue. Closing this one for now.

**Closed as completed by mregni** 2020-04-20 20:52 UTC
Labels: bug, duplicate
