### ISSUE TITLE
Support for Jellyfin 

### ISSUE THREAD

**Issue by CyberPoison** [mregni/EmbyStat#1088] opened 2020-02-23 13:48 UTC
# Feature request
Hello everyone, 

I would like to know if embystat works well with jellyfin, i don't have tested it but I'm interested to know if it already supports jellyfin.

Kind regards

**Comment by mregni** [comment] 2020-03-05 14:01
Duplicate of #1039, I'm going to upload a new beta version with support for Jellyfin soon! :)

**Closed as completed by mregni** 2020-03-05 14:01 UTC
