### ISSUE TITLE
Can't connect to Emby

### ISSUE THREAD

**Issue by kocane** [mregni/EmbyStat#1080] opened 2020-02-08 00:05 UTC
# Bug report

I can't for the life of me connect to the Emby server I'm running in a docker container next to EmbyStat. I also tried EmbyStat outside of docker to no avail. I can't even give you a log since nothing is being logged when I try to configure the server.

I've tried connecting with the localhost IP, external IP (with https and correct port) and also the docker IP (which EmbyStat discovers automatically). I can curl the IP and port inside the docker container and it displays the page correctly. I can also test that the API key works with `curl http://10.188.166.100:8096/emby/System/Info\?api_key\=keyhere`, and it returns output that connection works.

If I just press the "Final" button and go to the dashboard of EmbyStat, I can see that it is unconfigured without any connection to server. If I then try to configure it through this alternative configuration page, it now tells me that the API key isn't valid. I've tried creating new, of course, and tested them with above curl command and they work. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7694813/74074471-7c157500-4a0e-11ea-9f51-2eaee78361f7.png)

**System (please complete the following information):**

- OS: Debian Buster
- Browser Firefox
- Version v0.2.0-beta.15

**Comment by mregni** [comment] 2020-02-12 10:50
That's strange indeed that the authentication is failing of you can curl from inside the container. Normally there should be a log file in config/Logs folder. Did you check in that folder for logs?

**Comment by kocane** [comment] 2020-02-14 23:04
Yep, I did. It gives me nothing. I tried with 'Enable exception logging' too.

**Comment by mregni** [comment] 2020-03-05 13:52
That is strange, there should be at least some kind of log file in your container with some boot logging. If that is even not there then there is a bigger problem then just your api key. I'm trying to add some more logging in the wizard in the next release

**Comment by kocane** [comment] 2020-03-05 13:54
Cool, thanks. 

If you can let me know, in this issue (because I receive e-mail) when it should be ready for the testing, it would be great.

**Comment by specked** [comment] 2020-04-08 19:56
just upgraded today and now have this same issue. was working before. I'm using Unraid 6.8.3

**Comment by alkalinelito** [comment] 2020-04-09 22:17
Hi , I have the exact same problem trying to connect to Jellyfin,  trying to connect with curl works perfectly, but not in the wizard . 

Installed latest beta using package for Debian 10 , not docker.

**Comment by mregni** [comment] 2020-04-10 16:43
@alkalinelito, I created a new version with a --log-level parameter so I can see some more debug info.
Can you download this version and run it with the "--log-level 1" parameter? https://www.transfernow.net/5gOxHc042020

(this is a Debian build normally)

@kocane, I can't really create a docker container of this version. The extra log level will be added in beta.19 soon. If you tell me what OS you are running I can give you a version that you can run locally if you want.

**Comment by alkalinelito** [comment] 2020-04-11 00:19
Hi, just tried the build, but didn't launch the wizard. There's already a reggi user created, and can't find the setting to change it to Jellyfin on settings.       I replaced appsettings.json with a "new" one and removed usersettigns.json .

Now the wizard shows.

This is what the log showed when trying to connect to jellyfin server:

https://pastebin.com/AjJqv5dY

**Comment by mregni** [comment] 2020-04-11 06:38
ow, that's my id that was left in the build. Sorry about that!
I think you missed there because the pastebin contains the index.html file and not the log content :) 

Can you look for the log file in the "Logs" folder?

**Comment by alkalinelito** [comment] 2020-04-11 21:41
Hi, that's the content of the log file when you trying to connect to Jellyfin,  you see:

2020-04-10 21:15:31.4701 [DEBUG] SERVER-API Pinging server on http://localhost:23921
2020-04-10 21:15:31.4865 [DEBUG] BASE-HTTP-CLIENT   Ping returned <!DOCTYPE html>

and then just the index.html dump from jellyfin

**Comment by mregni** [comment] 2020-04-14 14:44
Missed that part, sorry. Seems like Jellyfin is returning his index page instead of the string "Jellyfin Server". That's why EmbyStat is thinking it's not finding the server.

I just tested it with Jellyfin 10.5.3 and I get this result when calling the ping API
![image](https://user-images.githubusercontent.com/22617019/79231727-cbd94800-7e66-11ea-83c7-7914de2b19d5.png)
No idea why you are getting the index page really. As you can see here I can also ping my Jellyfin server with Postman
![image](https://user-images.githubusercontent.com/22617019/79237913-034bf280-7e6f-11ea-9db8-ff702f89fdd7.png)
Can you try and test this on your pc? If you some error you can also try with the following header => X-Emby-Authorization=MediaBrowser RestClient="other", DeviceId="eb4837dc-8216-4741-a366-ad7427ebddfa", Device="EmbyStat", Version="0.0.0.0"

**Comment by alkalinelito** [comment] 2020-04-15 02:51
Hi , I got it to work ! (just the POST)

The problem is the url, I'm running Jellyfin  using a reverse proxy (nginx) in a remote server.

So the correct url would be : http://localhost:23921/jellyfin/System/Ping

(I'm using localhost , since I'm doing ssh port forwarding to test this problem)

I tested it with postman and it returns "Jellyfin Server" 

I need to append "/jellyfin" after the port number ,  couldn't do it in the wizard since it doesn't allow letters in port definition.


----
I have jellyfin configured this way:

![BaseURL](https://user-images.githubusercontent.com/62256/79294034-8ee37480-7eab-11ea-80cb-cd122588adab.jpg)

Using nginx with subpath way: https://jellyfin.org/docs/general/networking/nginx.html

**Comment by mregni** [comment] 2020-04-20 19:58
mmmm oke, I haven't got Nginx really working with EmbyStat. Is it maybe a good idea to add a "BaseUrl" input field in the wizard so you can add the "jellyfin" after your port number?

**Comment by alkalinelito** [comment] 2020-04-21 01:00
Yes, I think it's a good idea to add that option,  it seems it was also the problem of the creator of this issue since he had "emby" as base url too

**Comment by mregni** [comment] 2020-04-21 07:52
Yes indeed, but I never noticed that was the issue :) 
I'll add it to the beta.20 release. Thanks for testing!!

**Comment by alkalinelito** [comment] 2020-04-22 01:22
no problem, thank you for this project!

**Comment by mregni** [comment] 2021-08-02 06:59
This is normally fixed in a previous version, closing the issue for now. Feel free to reopen or create a new one if the issue is not fixed.

**Closed as completed by mregni** 2021-08-02 06:59 UTC
Labels: bug
