### ISSUE TITLE
MediaSync Fails on Windows10

### ISSUE THREAD

**Issue by alz41** [mregni/EmbyStat#98] opened 2018-07-11 12:39 UTC
**Describe the bug**

**To Reproduce**
goto Task
Click to run Media Sync
Get 'Last run 1 minute(s) and 17 second(s) ago, but failed after 24 second(s)'

Activity Window Shows:-

13:37:34 - Server plugins found
13:37:34 - Server drives found
13:37:34 - All server data is saved
13:38:06 - First delete all existing media and root media collections from database so we have a clean start.
13:38:06 - Lets start processing movies
13:38:06 - Asking for all root views for admin user with id 9dcf64add24e4f9db1ac221273eac6bf
13:38:06 - Found 1 movie root items, getting ready for processing
13:38:06 - Asking Emby all movies for parent (f137a2dd21bbc1b99aa5c0f6bf02a805) Movies
13:38:28 - Ready to add movies to database. We found 4592 movies

**System (please complete the following information):**
Windows10
Chrome

**Additional context**
[log20180710.txt](https://github.com/mregni/EmbyStat/files/2184431/log20180710.txt)

Let me Know if you need more info..

**Comment by mregni** [comment] 2018-07-11 12:53
Thanks for taking your time to log this issue!

It seems that while converting the Emby data to EmbyStat data something is going wrong. Seems to me like it is the same error as #74. I will prepare a version with more log output

**Comment by mregni** [comment] 2018-07-11 13:10
Duplicate of #74

**Comment by Happy2Play** [comment] 2018-07-11 18:29
I saw this behavior on version 0.1.0.0 but after updating to version 0.1.0.21 the tasks completed.

Shouldn't matter but I am on Emby beta server.

**Comment by alz41** [comment] 2018-07-13 01:04
Did some more testing today, 
turned on debug logging in emby resulting in the following entries
'2018-07-13 01:31:05.431 Debug BaseItem: Query requires post-filtering due to CollapseBoxSetItems
2018-07-13 01:31:06.571 Debug BaseItem: Query requires post-filtering due to LinkedChildren. Type: BoxSet
2018-07-13 01:31:06.681 Debug BaseItem: Query requires post-filtering due to LinkedChildren. Type: BoxSet
'
i then removed BoxSets from Emby, ran scan media library
and reloaded EmbyStat ran Media Sync with no problems

**Comment by alz41** [comment] 2018-07-13 01:06
Sorry Closed this issue by mistake

**Comment by Happy2Play** [comment] 2018-07-13 08:33
Reggi this appear to be a issue with Emby's "Group movies into collections" setting (Dashboard-Library-Display).  If enabled scan fails, disabling it scan finishes.

Side note I don't Group libraries but may have side effects also.  User icon-Home Screen-Library Folders
"Automatically group content from the following folders into views such as Movies, Music and TV:"

**Comment by mregni** [comment] 2018-07-13 08:42
@Happy2Play 
Thanks, I haven't tried that option in Emby. I have to check what happens with the data if you enable that setting

@alz41 Thanks for the Emby log, seems like I'm not preparing my call correctly then! I'm just finishing the language settings and then I will have a look at this.

**Comment by mregni** [comment] 2018-07-13 11:55
So, it seems that when you enable the boxset option on Emby it will send Boxset items even when you ask for Movie type items only. So I added a filter that will only process Movie type items. 

I will update the beta docker image this afternoon so you can test is again. I'll send a message when it is time.

**Comment by mregni** [comment] 2018-07-13 11:55
#74

**Comment by mregni** [comment] 2018-07-16 08:29
Guys, I push a new release to Gitub and Docker. 
Can you update to the newest version and see if you still see the error or not?

**Comment by mregni** [comment] 2018-07-16 13:13
Super, thanks for the feedback!

I'll wait for @alz41 to close the issue

**Comment by Happy2Play** [comment] 2018-07-17 01:49
Hmm, I get the same count whether collections are grouped or ungroup and I select Collections filter in top right and select each library it displays the same amount a each Movie All content type (Ungrouped).

What are you library content types?  As It looks like Stats only sees Movie and TV content types currently, my Mixed content library doesn't appear to be listed/counted.

**Comment by alz41** [comment] 2018-07-17 02:17
Group Movies In Collections Disabled
Collections Library = Mixed Content
Movie Library = Movie
Auto Box Sets Plugin Installed
Old Stats Plugin Reports 5032 Movies and 267 Collections
EmbyStats reports We found 5032 movies
This is as Expected.

Group Movies In Collections Enabled
Run Scan Media Library (Emby)
Old Stats Plugin Reports 5032 Movies and 267 Collections
EmbyStats We found 4599 movies

**Comment by Happy2Play** [comment] 2018-07-17 02:42
Okay if you want to compare the old plugin with this ststs server then okay yes there is a difference by from what I have read this is to be expected as of the content type counted.

I have 16 count difference between the two.  And I can see that same issue looking at Emby itself and the Reports plugin as I believe it is the count of all content types.  Personally I don't see a issue right now.

Total Movie count 3600
Movie Library 3081
Kids Library 519    Total 3600

Both Emby and Stats show this for 2 Libraries

But Old statistics plugin and Report shows 3616
For me the difference is the Fitness videos I have in a Mixed Content Library.

**Comment by mregni** [comment] 2018-07-17 07:12
At this moment, I'm indeed looking for libraries in Emby with type "Movies" or "TV". So movies in a "Mixed" type collection on Emby will be skipped for now.

I created an issue to fix this (#142), so Embystat will also look for movies and shows in the mixed libraries on Emby and nog only in "Movies" or "TV' typed libraries.

On the other hand, it is strange that EmbyStat is not finding all movies when the "Group Movies In Collections Enabled" is enabled. Since he will search recursively in all collections for movies as well. I'll test this on my test server and search for the movies that are skipped.

**Comment by mregni** [comment] 2019-02-27 13:04
Closing this issue because it should be fixed with #142, if not feel free to reply

**Closed** 2019-02-27 13:04 UTC
Labels: bug
