### ISSUE TITLE
Multi-episode files

### ISSUE THREAD

**Issue by ced455** [mregni/EmbyStat#1151] opened 2020-04-09 11:24 UTC
# Bug report

**Describe the bug**
Emby Stat does not recognize multiple episode in a single file. the software count the amount of file.

**To Reproduce**
name some file following the Multi-episode files section
https://support.emby.media/support/solutions/articles/44001159110-tv-naming

**Expected behavior**
We should get the amount of episode right

**Comment by Happy2Play** [comment] 2020-04-10 10:17
I think this may just be how Emby actually tracks these multi-episodes.  Example you have S01E01-E02 and play that item it is marked played, but if you delete that multi-episode and add S01E01 and S01E02, E02 will not be marked as played because E02 providerids don't actually exist.

Not sure how EmbyStats can actually curate these.

**Comment by mregni** [comment] 2020-04-10 15:45
Seems indeed like a bug, I'm just counting the entries and I will have to take into account the IndexNumber and IndexNumberEnd values so S01E01E02 will count as 2 instead of 1.

How I will handle the played state, later on, will be another problem :) Like Happy2Play stated it will be hard to keep track if you should change the files. I'll try to create a fix for the count now.

**Comment by ced455** [comment] 2020-04-10 16:42
Amazing, I use the multi episode feature like this : 01x01x13 to say season 1 episode one to season 1 episode 13 so 13 episodes !

Thank you for all your work

**Comment by mregni** [comment] 2020-04-10 16:45
Thanks :)

As long as Emby can read your way of working EmbyStat will work as well :)
Emby just has to update the IndexNumber and IndexNumberEnd and EmbyStat will pick it up (I'm going to merge this is beta.19)

**Comment by mregni** [comment] 2021-08-02 06:58
This is normally fixed in a previous version, closing the issue for now. Feel free to reopen or create a new one if the issue is not fixed.

**Closed as completed by mregni** 2021-08-02 06:58 UTC
Labels: bug
