### ISSUE TITLE
[Support] Various issues on linux

### ISSUE THREAD

**Issue by Ribesg** [mregni/EmbyStat#721] opened 2019-05-23 11:52 UTC
Hey, just tried to run EmbyStat, and failed in various ways. Here is a list of problems I encountered:

- [x] No documentation on volumes to mount
- [x] "Did you try to run a dotnet command?" message when attempting to mount `/app`
    I ended up mounting `/app/Logs` and `/app/Settings`, I found them in some other issues comments. I don't know if there is something else to mount. That's just what I've got currently.

- [x] `nightly-linux` docker image is a windows image
    Well this one is a wtf one :)

- [ ] Failed first sync in the Wizard: `POST https://<my-embystat-url>/api/emby/server/token 400 (Bad Request)`
    This was using the `beta-linux` image. Shouldn't this request be sent to the actual emby instance instead of the embystat one? They're both on the same server, and the embystat domain is stats.theembydomain

**Comment by hirenshah** [comment] 2019-05-24 22:02
I can confirm that nightly-linux for Windows lol :)

**Comment by mregni** [comment] 2019-05-25 07:39
LOL, thanks for the checklist!!

At the moment I can't rebuild the containers since I'm switching between build servers. But thanks for mentioning it!

As for the documentation, I know there is almost none at the moment. Since I don't have a stable beta release yet it changes a lot still. After the nosql update I will move the database to a folder that can be mounted. I still have no idea why we get the "did you try to run a dotnet command" error if you just mount the whole /app folder.

For the failed sync, I have to look into that. It indeed should go to the emby server and not to the embystat ofcourse.

I'll keep you posted on the bugs you logged, thanks for your time testing the app and reporting the bugs!

**Comment by mregni** [comment] 2019-07-20 17:15
So, I released a new beta version of the app yesterday. Can you check if you still have problems running the app?

`nightly-linux` tag has been renamed to `nightly-ubuntu-x64`

I will add some documentation on the docker page and github wiki for volumes to mount. basicly you can mount the following folder:

- /app/Logs
- /app/Database
- /app/Settings

**Comment by Ribesg** [comment] 2019-07-20 17:47
```Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/app/Settings/nlog.config'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at NLog.Config.LoggingConfigurationFileLoader.LoadXmlLoggingConfigurationFile(LogFactory logFactory, String configFile)
   at NLog.LogFactory.LoadConfiguration(String configFile)
   at NLog.LogManager.LoadConfiguration(String configFile)
   at EmbyStat.Web.Program.Main(String[] args) in d:\a\1\s\EmbyStat.Web\Program.cs:line 21
```

I tried to `touch` that specific file but it does not seem to work

**Comment by Ribesg** [comment] 2019-07-20 17:57
It actually ended up actually starting. Now I've got this:
![image](https://user-images.githubusercontent.com/1339686/61582246-8a5e7b00-ab28-11e9-9566-a224091682d9.png)

In the browser logs I see this:
```
POST https://<embyStatsUrl>/api/emby/server/ping 400 (Bad Request)
```

**Comment by mregni** [comment] 2019-07-20 20:25
Mmmmm, that doesn't seem good at all. What OS and package are you using for the moment and did you do a clean install?

That you see this is correct, the frontend will send a ping request to the backend, the backend will then send a ping to your Emby server. Could you check your logs for any exceptions in the Logs page or /app/Logs folder (for docker)?

**Comment by Ribesg** [comment] 2019-07-20 20:36
Running the nightly docker image on a Ubuntu 18.04.2 server.

The script I use to create/recreate the container:
```bash
IMAGE="uping/embystat:nightly-ubuntu-x64"
docker pull $IMAGE
docker create                                           \
        --name=embystats                                \
        --volume /home/embystats/Logs:/app/Logs         \
        --volume /home/embystats/Database:/app/Database \
        --volume /home/embystats/Settings:/app/Settings \
        --publish 1341:6555                             \
        --env UID=1005                                  \
        --env GID=1005                                  \
        --env PUID=1005                                 \
        --env PGID=1005                                 \
        --restart unless-stopped                        \
        $IMAGE
```

The important part of the nginx configuration:
```
        location / {
                proxy_pass http://localhost:1341;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

**Comment by mregni** [comment] 2019-07-20 21:01
Mmm, running as root isn't cool indeed. My experience with unix systems is limited so I have to do a lot of research for that first. I have a look at the Emby containers maybe!

As for the nlog.config that is missing. That is very strange since it's included in the docker build step. I'll check to make sure it's in the correct dir tomorrow. I can make the nightly Ubuntu container work on my machine. But that's a win10 using Linux containers, so not really a correct test anyway.

**Comment by leon1995** [comment] 2019-08-10 12:41
I have similar issues when trying to use embytats in docker on ubuntu 18.04.3 LTS 64bit.
I am using this docker-compose file:
```
version: '2'

services:
  embystats:
    container_name: embystats
    build: .
    volumes:
      - ./app/Database:/app/Database:rw
      - ./app/Logs:/app/Logs:rw
      - ./app/Settings:/app/Settings:rw
    environment:
      - VIRTUAL_HOST=embystats.domain.de
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=5432
      - LETSENCRYPT_HOST=embystats.domain.de
      - LETSENCRYPT_EMAIL=mail@domain.de
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

and this Dockerfile:
```
FROM microsoft/dotnet:2.2.1-runtime as base
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
LABEL author="UPing"

WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "EmbyStat.dll", "--server.urls", "http://0.0.0.0:80"]
```
But I get the following errors
```
Attaching to embystats
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
embystats    | Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
embystats    |   https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

**Comment by mregni** [comment] 2019-08-12 05:11
@leon1995 

- VIRTUAL_PORT needs to be 6555 (I needed to change it because there was a conflict with a Synology service on that port)
- only /app/config needs to be mounted as of now.

As for the error, I presume it's because of the server.urls setting you are passing int EmbyStat. If you want to change the port that EmbyStat is running use the --port option. Can you try the following entry point and see if it works?
`ENTRYPOINT ["dotnet", "EmbyStat.dll", "--port", "80"]`

I'm not sure but I think you have to update the VIRTUAL_PORT in your docker-compose file to the same port you are running EmbyStat on?

**Comment by leon1995** [comment] 2019-08-12 20:18
changed VIRTUAL_PORT to 6555, and the entrypoint changes. also only mounted /app/config.
also tried with `ENTRYPOINT ["dotnet", "EmbyStat.dll"]` but i still got the same issue

**Comment by leon1995** [comment] 2019-08-12 20:29
basically when i use your docker image then it works. but i want to use it within my nginx network. therefore i build this docker-compose file
```
version: '2'

services:
  embystats:
    image: uping/embystat:latest-linux
    container_name: embystats
    volumes:
      - ./app/config:/app/config:rw
    environment:
      - VIRTUAL_HOST=embystats.domain.de
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=6555
      - LETSENCRYPT_HOST=embystats.domain.de
      - LETSENCRYPT_EMAIL=mail@domain.de
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
`$ docker logs embystats`
```
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

but then i cant reach the container even though my proxy is correct (it works on other container)

EDIT: maybe its because the container is running locally with the url `http://[::]:80`?

**Comment by mregni** [comment] 2019-08-13 15:16
There was someone else on the forum why had problems with running this with docker-compose and volumes. I think if you remove the mounting points it may work (but then you have no volumes, so not really a solution)

**Comment by leon1995** [comment] 2019-08-15 14:34
Havent found what you mean :(

Hos can I reach the server when running it in docker using `docker run -p 6555 uping/embystat:latest-linux`? `localhost:6555` or `localhost:80` in the browser doesnt work.

This is my response from starting it:
```
$ docker run -p 6555 uping/embystat:latest-linux
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
```

It confuses me that even when i specify a port using -p 6555 the container says its listeninig on `http://[::]:80`. (What does `[::]` even mean?)

**Comment by mregni** [comment] 2019-08-17 10:05
the -p flag is wrong formed I guess. try the following command:
`docker run -p 6555:6555 uping/embystat:beta-ubuntu-x64`

This will map the 6555 port on your host to the 6555 port in the container (EmbyStat is running on 6555 by default)

Also, don't use the latest-linux container since it's not update at the moment. I'll remove it from the docker hub asap.

**Comment by leon1995** [comment] 2019-08-19 08:13
using `beta-ubuntu-x64` and
```
ports:
  - 6555:6555
```
beside of the environment stuff works. but as you mentioned i cannot mount directories. so when i restart the container i have to configure it again.

As a feature request:
Is it possible to add a password for authentication the user?
Is it possible to add the emby movies/shows as a directory in embystats so i dont have to download them into the container and have the movies take storage twice

**Comment by Ribesg** [comment] 2019-08-20 13:35
I just tried the current nightly and the bug where EmbyStat calls itself instead of the Emby instance is still here, when do you plan to fix it?

**Comment by mregni** [comment] 2019-08-20 13:52
@leon1995, the movies/shows are is never downloaded inside the container. What the sync does is sync all necessary data from Emby from all your movies and shows. So, in the end, you will have a database of 50Mb.

@Ribesg, can you tell me what call is made to EmbyStat instead of Emby?

**Comment by Ribesg** [comment] 2019-08-20 13:54
`https://<MyEmbyStatHost>/api/emby/server/ping` during the "Emby Sync" phase of the Wizard.

My EmbyStat host is basically `stats.<MyEmbyHost>`, if that helps.

**Comment by mregni** [comment] 2019-08-20 14:04
That seems to be the correct behaviour, EmbyStat backend will ping your Emby server. The UI is just calling the correct backend function on the `https://<MyEmbyStatHost>/api/emby/server/ping` url. Are you blocked on the wizard because the first check if failing? If so, that's another bug.

**Comment by Ribesg** [comment] 2019-08-20 14:26
Well this request returns a 400, and the Next button stays gray

**Comment by leon1995** [comment] 2019-08-24 16:05
@mregni ok thats nice to know. what about the password?

**Comment by mregni** [comment] 2019-08-26 09:56
@leon1995, sorry, I didn' see that feature request. What you mean exactly with "Is it possible to add a password for authentication the user?" At the moment you have to use your password to get an authentication token from Emby in the wizard. What other place did you have in mind to authenticate a user?

I do have a feature request to add user authentication on EmbyStat itself. But that will be a big feature and I first want to make EmbyStat a bit more stable and runnable on all kinds of systems.

**Comment by leon1995** [comment] 2019-08-27 19:14
sorry that was a bit unclear. I do mean a user authentication to embystat itself. im glad to hear that its already on the list! :)

**Comment by mregni** [comment] 2019-09-25 21:06
@leon1995, can you try again with the beta.11 version? I added some support for Nginx in the server and for someone on the Emby forum it's working now :)

**Comment by leon1995** [comment] 2019-10-12 12:31
Its working with the following `docker-compose.yml` file:
```
version: '2'

services:
  embystats:
    image: uping/embystat:beta-ubuntu-x64
    container_name: embystats
    volumes:
      - ./app/config:/app/config:rw
    ports:
      - 6555:6555
    restart: always
```

Are you working on that authenticaion thing? I mean, like that you have to authenticate with a username and password before entering embystats itself (like you have to log in before using twitter etc..).
Thanks for the help!

**Comment by mregni** [comment] 2019-10-14 08:49
That's on my backlog as well yes. Not working on it currently because I still have to fix the memory issue before anything else. Thanks for the docker-compose file!

When I can start working on new features, I will implement a login feature yes :)

**Comment by Ribesg** [comment] 2019-10-27 13:14
Can you please not close issues unless they're fixed, thanks

**Comment by mregni** [comment] 2019-11-06 06:55
Forgot to remove the question label, sorry :)

**Comment by Ribesg** [comment] 2020-02-12 09:50
Tried again today with the latest `uping/embystat:beta`, no change

**Comment by mregni** [comment] 2020-03-05 13:50
@Ribesg, do you have access to the EmbyStat log files? It should log the exception you are getting in the backend (if any)

**Comment by mregni** [comment] 2022-06-13 11:32
Going to close this issue for now. If there are still some issues found please create a new one

**Closed by mregni** 2022-06-13 11:32 UTC
Labels: bug
