### ISSUE TITLE
Movie synchronization failed

### ISSUE THREAD

**Issue by Floflobel** [mregni/EmbyStat#74] opened 2018-05-11 15:39 UTC
**Describe the bug**
The movie synchronization failed 

**To Reproduce**
1. Go to the section task 
2. Run "Movie Sync"

**Expected behavior**
When I launch the docker I have this notification at the right of my page 

`EXCEPTIONS.An unhandled error occurred. `

Into the task section when I run "Movie sync"
```
Movie sync
Last run 1 second(s) ago, but failed after 3 second(s)
```

**System (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Firefox

**Additional context**
I try to get the log but I do not know well docker. The docker log command does not get me anything.

**Comment by mregni** [comment] 2018-05-11 16:09
Thanks for logging the issue. I'm working a log page so you can see the real log files the app logs. IN a few days I will upload a major update. So let's see if your error is still coming up after the update.

**Comment by jaycedk** [comment] 2018-07-10 08:41
Hi any news about this issue.
Just installed latest docker, and seeing this issue as well.

Movie sync
Last run 8 hour(s) , 33 minute(s) and 58 second(s) ago, but failed after 5 minute(s) and 10 second(s)

**Comment by mregni** [comment] 2018-07-10 08:48
I'm going to do a massive update to BETA this night, this will include movies, shows and an easy way to download the server log files. 

So let's see if the issue is still there after tomorrow. Please keep me posted on this!

**Comment by jaycedk** [comment] 2018-07-10 08:51
Cool :) 
Will keep you posted.

**Comment by jaycedk** [comment] 2018-07-11 06:08
Good job :)
Everything work.
Thank you.

**Comment by mregni** [comment] 2018-07-11 08:20
Super glad to hear that!

I'll close this issue now. If there is still a problem just create a new issue.

**Comment by Floflobel** [comment] 2018-07-11 09:22
The issue is still present for me..
How I can show log ?

**Comment by mregni** [comment] 2018-07-11 09:31
Oke, let's reopen this issue then :)

In the menu, there should be a "Logs" menu item now (since beta release yesterday), click on the menu item and you should see all kinds of log files ready for download

![image](https://user-images.githubusercontent.com/22617019/42563086-a643d722-84fd-11e8-80cf-a2c5d8bb1404.png)

If you don't see the new Logs menu item you didn't update to the last Beta version. Go to [https://github.com/mregni/EmbyStat/releases](url) and download the 0.1.0.21-beta version.

**Comment by Floflobel** [comment] 2018-07-11 09:42
Actually I had not updated to the latest version. I am not very relaxed with docker. The error is still present in this version.
This time it's good, here are the logs:

`2018-07-11 09:36:54 [INF] Booting up server
2018-07-11 09:36:57 [INF] Migrating database started
2018-07-11 09:36:59 [INF] Migrating database ended
2018-07-11 09:36:59 [INF] Initialising configuration
2018-07-11 09:37:00 [INF] Daily trigger for TASKS.SMALLEMBYSYNCTITLE set to fire at 07/12/2018 00:30:00, which is 892.991816156667 minutes from now.
2018-07-11 09:37:00 [INF] Daily trigger for TASKS.MEDIASYNCTITLE set to fire at 07/12/2018 00:00:00, which is 862.991641325 minutes from now.
2018-07-11 09:37:15 [INF] Getting server configuration from database.
2018-07-11 09:37:15 [INF] Searching for an Emby server in the network and returning the IP address.
2018-07-11 09:37:35 [INF] Get emby token for certain login credentials.
2018-07-11 09:37:35 [ERR] EMBY_CALL_FAILED
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.CreateHttp(String requestUriString)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestFactory.Create(HttpRequest options) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestFactory.cs:line 15
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<GetResponse>d__2.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<SendAsync>d__5.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<SendAsync>d__58.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<PostAsync>d__53`1.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 218
2018-07-11 09:37:35 [ERR] Username or password are wrong, user should try again with other credentials!
2018-07-11 09:37:35 [ERR] Message: EMBY_CALL_FAILED
2018-07-11 09:37:35 [WRN] Application thrown error: TOKEN_FAILED
2018-07-11 09:37:35 [WRN] Frontend will know what to do with this!
2018-07-11 09:37:43 [INF] Get emby token for certain login credentials.
2018-07-11 09:37:43 [ERR] EMBY_CALL_FAILED
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.CreateHttp(String requestUriString)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestFactory.Create(HttpRequest options) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestFactory.cs:line 15
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<GetResponse>d__2.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<SendAsync>d__5.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<SendAsync>d__58.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<PostAsync>d__53`1.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 218
2018-07-11 09:37:43 [ERR] Username or password are wrong, user should try again with other credentials!
2018-07-11 09:37:43 [ERR] Message: EMBY_CALL_FAILED
2018-07-11 09:37:43 [WRN] Application thrown error: TOKEN_FAILED
2018-07-11 09:37:43 [WRN] Frontend will know what to do with this!
2018-07-11 09:37:56 [INF] Get emby token for certain login credentials.
2018-07-11 09:37:56 [ERR] EMBY_CALL_FAILED
System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.CreateHttp(String requestUriString)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestFactory.Create(HttpRequest options) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestFactory.cs:line 15
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<GetResponse>d__2.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.Net.HttpWebRequestClient.<SendAsync>d__5.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/Net/HttpWebRequestClient.cs:line 123
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<SendAsync>d__58.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Api.EmbyClient.BaseClient`1.<PostAsync>d__53`1.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Api/EmbyClient/BaseClient.cs:line 218
2018-07-11 09:37:56 [ERR] Username or password are wrong, user should try again with other credentials!
2018-07-11 09:37:56 [ERR] Message: EMBY_CALL_FAILED
2018-07-11 09:37:56 [WRN] Application thrown error: TOKEN_FAILED
2018-07-11 09:37:56 [WRN] Frontend will know what to do with this!
2018-07-11 09:38:18 [INF] Get emby token for certain login credentials.
2018-07-11 09:38:19 [INF] Updating the new server configuration.
2018-07-11 09:38:19 [INF] Sync basic Emby server info.
2018-07-11 09:38:26 [INF] Getting all background tasks.
2018-07-11 09:38:27 [INF] Executing TASKS.MEDIASYNCTITLE
2018-07-11 09:38:27 [INF] First delete all existing media and root media collections from database so we have a clean start.
2018-07-11 09:38:28 [INF] Lets start processing movies
2018-07-11 09:38:28 [INF] Asking for all root views for admin user with id 4bb14b9730e0495a9658de133c2425bd
2018-07-11 09:38:28 [INF] Found 1 movie root items, getting ready for processing
2018-07-11 09:38:28 [INF] Asking Emby all movies for parent (db4c1708cbb5dd1676284a40f2950aba) Films
2018-07-11 09:38:32 [INF] Ready to add movies to database. We found 373 movies
2018-07-11 09:38:32 [ERR] Error
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at EmbyStat.Common.Converters.MovieHelper.ConvertToMovie(BaseItemDto x) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Common/Converters/MovieHelper.cs:line 15
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<ProcessMovies>d__21.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<Execute>d__19.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.ScheduledTaskWorker.<ExecuteInternal>d__54.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/ScheduledTaskWorker.cs:line 231
2018-07-11 09:38:32 [INF] TASKS.MEDIASYNCTITLE "Failed" after 0 minute(s) and 4 seconds
2018-07-11 09:38:32 [INF] ExecuteQueuedTasks
2018-07-11 09:38:48 [INF] Executing TASKS.MEDIASYNCTITLE
2018-07-11 09:38:48 [INF] First delete all existing media and root media collections from database so we have a clean start.
2018-07-11 09:38:48 [INF] Lets start processing movies
2018-07-11 09:38:48 [INF] Asking for all root views for admin user with id 4bb14b9730e0495a9658de133c2425bd
2018-07-11 09:38:48 [INF] Found 1 movie root items, getting ready for processing
2018-07-11 09:38:48 [INF] Asking Emby all movies for parent (db4c1708cbb5dd1676284a40f2950aba) Films
2018-07-11 09:38:52 [INF] Ready to add movies to database. We found 373 movies
2018-07-11 09:38:52 [ERR] Error
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at EmbyStat.Common.Converters.MovieHelper.ConvertToMovie(BaseItemDto x) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Common/Converters/MovieHelper.cs:line 15
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<ProcessMovies>d__21.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<Execute>d__19.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.ScheduledTaskWorker.<ExecuteInternal>d__54.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/ScheduledTaskWorker.cs:line 231
2018-07-11 09:38:52 [INF] TASKS.MEDIASYNCTITLE "Failed" after 0 minute(s) and 4 seconds
2018-07-11 09:38:52 [INF] ExecuteQueuedTasks
2018-07-11 09:38:56 [INF] Executing TASKS.SMALLEMBYSYNCTITLE
2018-07-11 09:38:56 [INF] Server info found
2018-07-11 09:38:56 [INF] Server plugins found
2018-07-11 09:38:56 [INF] Server drives found
2018-07-11 09:38:56 [INF] All server data is saved
2018-07-11 09:38:56 [INF] TASKS.SMALLEMBYSYNCTITLE "Completed" after 0 minute(s) and 0 seconds
2018-07-11 09:38:56 [INF] ExecuteQueuedTasks
2018-07-11 09:38:58 [INF] Executing TASKS.PINGEMBYSERVERTITLE
2018-07-11 09:38:58 [INF] TASKS.PINGEMBYSERVERTITLE "Completed" after 0 minute(s) and 0 seconds
2018-07-11 09:39:10 [INF] Executing TASKS.MEDIASYNCTITLE
2018-07-11 09:39:10 [INF] First delete all existing media and root media collections from database so we have a clean start.
2018-07-11 09:39:11 [INF] Lets start processing movies
2018-07-11 09:39:11 [INF] Asking for all root views for admin user with id 4bb14b9730e0495a9658de133c2425bd
2018-07-11 09:39:11 [INF] Found 1 movie root items, getting ready for processing
2018-07-11 09:39:11 [INF] Asking Emby all movies for parent (db4c1708cbb5dd1676284a40f2950aba) Films
2018-07-11 09:39:15 [INF] Ready to add movies to database. We found 373 movies
2018-07-11 09:39:15 [ERR] Error
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at EmbyStat.Common.Converters.MovieHelper.ConvertToMovie(BaseItemDto x) in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Common/Converters/MovieHelper.cs:line 15
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<ProcessMovies>d__21.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.Tasks.MediaSyncTask.<Execute>d__19.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/Tasks/MediaSyncTask.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EmbyStat.Tasks.ScheduledTaskWorker.<ExecuteInternal>d__54.MoveNext() in /opt/teamcity/work/aa794b64fcf59423/EmbyStat.Tasks/ScheduledTaskWorker.cs:line 231
2018-07-11 09:39:15 [INF] TASKS.MEDIASYNCTITLE "Failed" after 0 minute(s) and 4 seconds
2018-07-11 09:39:15 [INF] ExecuteQueuedTasks`

**Comment by mregni** [comment] 2018-07-11 09:54
Thanks for the log! Seems like you have a ArgumentNullException 
Aaaaaaarghhhh!!

looks like converting the emby data to embystat data is going wrong somehow. 
I'll have to create a new release with more logging for you. I'll send you an update when I have it ready for you this night.

**Comment by Floflobel** [comment] 2018-07-11 09:59
Thank you for the responsiveness I expect this release then

**Comment by mregni** [comment] 2018-07-13 11:57
Can you check if the Boxset option is enabled on your system? If so I have found a fix. It seems that when you enable the boxset option on Emby it will send Boxset items even when you ask for Movie type items only. So I added a filter that will only pass Movie type items.

I will update the beta docker image this afternoon so you can test is again. I'll send a message when it is time.

**Comment by mregni** [comment] 2018-07-16 08:30
@Floflobel 
I pushed a new beta version to Github and Docker. Can you update your local version and check if you still see the error?

**Comment by mregni** [comment] 2018-07-16 08:32
Closed by mistake

**Comment by Floflobel** [comment] 2018-07-16 15:50
The error is solved thank you for your works. 
I have a question the Boxset movies isn't count ?

**Comment by mregni** [comment] 2018-07-24 11:57
I release a new version yesterday. Now Boxsets are searched recursively for movies as well. 
So if you have the following situation:

-Movie Collection
  -Movie 1
  -Movie2
  -BoxSet1
      -Movie3
      -Movie4
  -BoxSet2
      -Movie5
      -Movie6

The sync will find 6 movies now instead of just 2 in the previous release.

I'm going to close this issue, if you find some new bugs or questions feel free to open a new issue.

**Closed by mregni** 2018-07-24 11:57 UTC
Labels: bug
