### ISSUE TITLE
Shows gives an error

### ISSUE THREAD

**Issue by Celsiusss** [mregni/EmbyStat#1081] opened 2020-02-10 16:35 UTC
# Bug report

**Describe the bug**
Navigating to shows makes an error with `Unhandled backend exception` in the lower left corner.

**To Reproduce**

1. Go to Shows
2. See error

**Expected behavior**
Shows stats should show

**Screenshots**

**System (please complete the following information):**

- OS: UNRAID running latest linuxserver/embystat docker
- Browser: Chrome
- Version 79

**Additional context**
![image](https://user-images.githubusercontent.com/3050747/74169118-18b45e80-4c2b-11ea-9bfc-32bdb69855e0.png)

![image](https://user-images.githubusercontent.com/3050747/74169141-210c9980-4c2b-11ea-8363-c0b6cded77ca.png)

Server log:
```
2020-02-10 17:27:26.2439 [ERROR] An unhandled error occurred. System.Collections.Generic.KeyNotFoundException: The given key '51' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LiteDB.IndexService.Find(CollectionIndex index, BsonValue value, Boolean sibling, Int32 order)
   at LiteDB.QueryEquals.ExecuteIndex(IndexService indexer, CollectionIndex index)+MoveNext()
   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___|0>d.MoveNext()
   at LiteDB.QueryCursor.Fetch(TransactionService trans, DataService data, BsonReader bsonReader)
   at LiteDB.LiteEngine.Find(String collection, Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at LiteDB.LiteEngine.FindById(String collection, BsonValue id)
   at LiteDB.LiteEngine.Find(String collection, Query query, String[] includes, Int32 skip, Int32 limit)+MoveNext()
   at LiteDB.LiteCollection`1.Find(Query query, Int32 skip, Int32 limit)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EmbyStat.Repositories.ShowRepository.<>c__DisplayClass6_0.<GetAllShows>b__0() in d:\a\1\s\EmbyStat.Repositories\ShowRepository.cs:line 118
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery[T1](Func`1 query) in d:\a\1\s\EmbyStat.Repositories\BaseRepository.cs:line 21
   at EmbyStat.Services.ShowService.TotalEpisodeCount(IReadOnlyList`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 188
   at EmbyStat.Services.ShowService.CalculateGeneralStatistics(IReadOnlyList`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 81
   at EmbyStat.Services.ShowService.CalculateShowStatistics(List`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 59
   at EmbyStat.Services.ShowService.GetStatistics(List`1 libraryIds) in d:\a\1\s\EmbyStat.Services\ShowService.cs:line 54
   at EmbyStat.Controllers.Show.ShowController.GetStatistics(List`1 libraryIds) in d:\a\1\s\EmbyStat.Controllers\Show\ShowController.cs:line 36
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

**Comment by Nestar47** [comment] 2020-02-15 18:39
I'm also having this issue (Debian x64 2.0 Beta 15)

It appears to be due to shows sync not completing

The error appears directly after finishing processing Show 25/541 (Altered Carbon) but before it shows any progress on Show 26 (Assuming alphabetical order, it would be American Vandal)
2020-02-15 12:28:29.4466 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Converters.ShowConverter.<>c.<ConvertToShow>b__0_7(BaseItemPerson x) in /home/vsts/work/1/s/EmbyStat.Common/Converters/ShowConverter.cs:line 41
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EmbyStat.Common.Converters.ShowConverter.ConvertToShow(BaseItemDto show, String collectionId) in /home/vsts/work/1/s/EmbyStat.Common/Converters/ShowConverter.cs:line 17
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 220
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 202
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 54
2020-02-15 12:28:29.4856 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-02-15 12:28:29.6442 [WARN] Failed to process the job 'e73aa23e-ec8f-4a8b-bcfc-4f53339705e6': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:37. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Common.Converters.ShowConverter.<>c.<ConvertToShow>b__0_7(BaseItemPerson x) in /home/vsts/work/1/s/EmbyStat.Common/Converters/ShowConverter.cs:line 41
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at EmbyStat.Common.Converters.ShowConverter.ConvertToShow(BaseItemDto show, String collectionId) in /home/vsts/work/1/s/EmbyStat.Common/Converters/ShowConverter.cs:line 17
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 220
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 202
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 85
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by mregni** [comment] 2020-03-05 13:56
Looks like some data is missing while running the sync indeed. That's why you get a null ref exception. I will create a night build so we can see what missing property is. Give me a few hours!

**Comment by Nestar47** [comment] 2020-03-06 05:07
My movies have now started doing it instead now. Different error on that one.

2020-03-05 23:00:14.9112 [WARN] Failed to process the job '9abf784f-2f6c-42e7-b118-14a2c7d5dea2': an exception occurred. Retry attempt 1 of 2 will be performed in 00:00:31. System.InvalidCastException: Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.IndexPage'.
   at LiteDB.PageService.GetPage[T](UInt32 pageID)
   at LiteDB.IndexService.Delete(CollectionIndex index, PageAddress nodeAddress)
   at LiteDB.LiteEngine.<>c__DisplayClass8_0.<Delete>b__0(CollectionPage col)
   at LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   at EmbyStat.Repositories.MovieRepository.<RemoveMovies>b__15_0() in /home/vsts/work/1/s/EmbyStat.Repositories/MovieRepository.cs:line 287
   at EmbyStat.Repositories.BaseRepository.ExecuteQuery(Action query) in /home/vsts/work/1/s/EmbyStat.Repositories/BaseRepository.cs:line 29
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessMoviesAsync(IReadOnlyList`1 libraries, CancellationToken cancellationToken) in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 98
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync() in /home/vsts/work/1/s/EmbyStat.Jobs/Jobs/Sync/MediaSyncJob.cs:line 82
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 54
   at EmbyStat.Jobs.BaseJob.Execute() in /home/vsts/work/1/s/EmbyStat.Jobs/BaseJob.cs:line 66
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by Nestar47** [comment] 2020-04-10 17:25
The movies error above has gone away with release 18, shows now fail before any are processed though.

2020-04-10 12:23:31.1908 [INFO] MEDIASYNC-JOB	Lets start processing show 
2020-04-10 12:23:31.1908 [INFO] MEDIASYNC-JOB	Logging in on the Tvdb API. 
2020-04-10 12:23:31.1908 [INFO] THETVDB-CLIENT	Logging in on theTVDB API with key: xxxxxxxxxxxxxx 
2020-04-10 12:23:32.7847 [ERROR] Error while running job System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Converters.ShowConverter.<>c.<ConvertToShow>b__0_7(BaseItemPerson x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at EmbyStat.Clients.Base.Converters.ShowConverter.ConvertToShow(BaseItemDto show, String LibraryId)
   at EmbyStat.Clients.Base.Http.BaseHttpClient.<>c__DisplayClass46_0.<GetShows>b__0(BaseItemDto x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetShows(String parentId)
   at EmbyStat.Clients.Emby.Http.EmbyHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetShows(String libraryId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
2020-04-10 12:23:32.8021 [ERROR] MEDIASYNC-JOB	Job failed, check logs for more info. 
2020-04-10 12:23:32.9427 [WARN] Failed to process the job 'ae635ba9-84e9-4245-aa61-28286b6e87f4': an exception occurred. Retry attempt 2 of 2 will be performed in 00:00:36. System.NullReferenceException: Object reference not set to an instance of an object.
   at EmbyStat.Clients.Base.Converters.ShowConverter.<>c.<ConvertToShow>b__0_7(BaseItemPerson x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at EmbyStat.Clients.Base.Converters.ShowConverter.ConvertToShow(BaseItemDto show, String LibraryId)
   at EmbyStat.Clients.Base.Http.BaseHttpClient.<>c__DisplayClass46_0.<GetShows>b__0(BaseItemDto x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at EmbyStat.Clients.Base.Http.BaseHttpClient.GetShows(String parentId)
   at EmbyStat.Clients.Emby.Http.EmbyHttpClient.EmbyStat.Clients.Base.Http.IHttpClient.GetShows(String libraryId)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.PerformShowSyncAsync(IReadOnlyList`1 showsThatNeedAnUpdate, Library library, DateTime updateStartTime)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.ProcessShowsAsync(IEnumerable`1 libraries, CancellationToken cancellationToken)
   at EmbyStat.Jobs.Jobs.Sync.MediaSyncJob.RunJobAsync()
   at EmbyStat.Jobs.BaseJob.Execute()
   at EmbyStat.Jobs.BaseJob.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by mregni** [comment] 2020-04-10 20:40
That looks like it is missing some data from Emby while it is syncing. I'm going to catch doesn't null reference exception in a null check. Hopefully will be fixed in beta.19

**Comment by mregni** [comment] 2021-08-02 06:59
This is normally fixed in a previous version, closing the issue for now. Feel free to reopen or create a new one if the issue is not fixed.

**Closed as completed by mregni** 2021-08-02 06:59 UTC
Labels: bug
